# Generated by Django 5.1.2 on 2024-11-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="codigo_de_barras",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="quantidade_atual",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="quantidade_minima",
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
